services:
  - type: web
    name: video-processing-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GOOGLE_API_KEY
        sync: false 